version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: softhub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  redis:
    image: redis:7
    ports:
      - '6379:6379'

  core_api:
    build: ./services/core_api
    volumes:
    - ./services/core_api/app:/app/app
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/softhub
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    ports:
      - '8000:8000'

  worker:
    build: ./services/worker
    depends_on:
      - redis

  webapp:
    build: ./services/webapp
    volumes:
    - ./services/webapp:/app
    - /app/node_modules
    depends_on:
      - core_api
    ports:
      - '5173:5173'
